### PR TITLE
Added tracking scripts for Alexa and Google

### PR DESCRIPTION
**Pull request by mrkiley**

### CODE REVIEW

**Comment by archisgore** [comment]
looking...

**Comment by archisgore** [comment]
Lines 71 through 79 already have a google analytics tag. You should see "Binary Entropy Visualizer" in the Google Analytics page (the working title I had before EnVisen.)

You can remove that if you'd like, but only keep one.

**Comment by mrkiley** [comment]
@archisgore, updated it

**Comment by archisgore** [comment]
LGTM

**Pull request merged**
